---
# tasks file for haproxy

  - name: Install packages
    yum:
     name: "{{ item }}"
     state: latest
    with_items:
     - httpie
     - haproxy
    notify: 
     - enable HAProxy

  - name: configure haproxy
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
     - restart HAProxy

  - name: Start haproxy if it isn't running
    service:
     name: haproxy
     enabled: true
     state: started
