---

- name: deploy haproxy
  hosts: frontends
  gather_facts: true
  become: true

  vars:
   - include_vars: vault.yml

  roles:
   - { name: common }
   - { role: haproxy }

- name: deploy tomcat
  hosts: apps
  gather_facts: true
  become: true

  vars:
   - include_vars: vault.yml

  roles:
   - { name: common }
   - { role: tomcat }

- name: deploy postgres
  hosts: apps
  gather_facts: true
  become: true
  hosts: appdbs

  vars:
   - include_vars: vault.yml

  roles:
   - { name: common }
   - { role: geerlingguy.postgresql }

- name: deploy apache
  hosts: apps
  gather_facts: false
  become: true
  hosts: apps

  vars:
   - include_vars: vault.yml

  roles:
   - { name: common }
   - { role: apache }
