---
# tasks file for tomcat

  - name: install tomcat
    yum:
      name: tomcat
      state: latest
    notify: 
     - enable tomcat

  - name: create ansible tomcat directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
     - /usr/share/tomcat/webapps/ROOT
     - /usr/share/tomcat/webapps/ansible

  - name: copy static index.html to tomcat webapps/ansible/index.html
    template:
      src: index.html.j2
      dest: /usr/share/tomcat/webapps/ROOT/index.html
      mode: 0644
    with_items:
     - { name: "index.html.j2" , path: "/usr/share/tomcat/webapps/ROOT/index.html" }
    notify: 
     - restart tomcat

  - name: Start tomcat if it is not running
    service: 
      name: tomcat
      enabled: true
      state: started
